// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.raze.diplomado.seguridad.tarea9.domain;

import com.raze.diplomado.seguridad.tarea9.domain.Catalogo1DataOnDemand;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect Catalogo1DataOnDemand_Roo_Configurable {
    
    declare @type: Catalogo1DataOnDemand: @Configurable;
    
}
